CREATE TABLE IF NOT EXISTS funcionario (
    id_funcionario SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sexo SMALLINT NOT NULL,
    data_nascimento DATE NOT NULL,
    whatsapp VARCHAR(16) NULL,
    telefone VARCHAR(16) NULL,
    rg VARCHAR(45) NULL,
    orgao_expedidor VARCHAR(10) NULL,
    data_expedicao DATE NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    mae VARCHAR(255) NULL,
    naturalidade VARCHAR(100) NULL,
    matricula VARCHAR(8) NULL,
    escolaridade VARCHAR(45) NULL,
    cargo VARCHAR(45) NULL,
    funcao VARCHAR(45) NULL,
    vinculo VARCHAR(45) NULL,
    empresa VARCHAR(45) NULL,
    data_admissao DATE NULL,
    carga_horaria INT NULL,
    data_criacao DATE NOT NULL,
    data_atualizacao DATE NOT NULL,
    id_endereco INT REFERENCES endereco(id_endereco) ON DELETE CASCADE ON UPDATE CASCADE
)